#!/usr/bin/env python3
"""Audit the direct SAC-restoration axis for Track 2, per plan sections 7.1-7.2.

Asks one question end to end: if we nominate targets by signed causal edges from
the MVA seed genes, do drugs exist that act in the direction the biology
requires? Writes results/summaries/track2_direction_audit.md.
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, "src")

from mva.track2.targets import Direction, fetch_signed_edges, nominate, summarise
from mva.track2.tractability import Tractability, assess

SEEDS = {"BUB1B", "CEP57", "TRIP13", "BUB1", "BUB3", "CEP192", "SMC5", "CENATAC"}

def main() -> None:
    edges = fetch_signed_edges(sorted(SEEDS))
    partners: dict[str, list] = {}
    for es in edges.values():
        for e in es:
            if e.target in SEEDS and e.source not in SEEDS:
                partners.setdefault(e.source, []).append(e)

    noms = [nominate(g, es, SEEDS) for g, es in partners.items()]
    s = summarise(noms)

    results = []
    for n in noms:
        if n.is_nominable:
            results.append((n, assess(n.gene, n.direction)))

    out = pathlib.Path("results/summaries/track2_direction_audit.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    L = []
    L.append("# Track 2: is the direct SAC-restoration axis tractable?\n")
    L.append("Generated by `scripts/14_track2_direction_audit.py`. Sources: OmniPath")
    L.append("signed causal edges, ChEMBL drug mechanisms.\n")
    L.append("## Question\n")
    L.append("The proband's mechanism is a hypomorphic spindle assembly checkpoint. The")
    L.append("obvious therapeutic idea is to restore checkpoint activity. Plan section 7.2")
    L.append("requires a stated direction per target; this audit then asks whether any drug")
    L.append("acts in that direction.\n")
    L.append("## Target nomination\n")
    L.append(f"- candidate modulators with a signed edge into a seed gene: **{s['n_total']}**")
    L.append(f"- direction resolved: **{s['n_nominable']}** "
             f"(activate {len(s['activate'])}, inhibit {len(s['inhibit'])})")
    L.append(f"- rejected, contradictory sign: {len(s['rejected_ambiguous'])} "
             f"{', '.join(s['rejected_ambiguous']) or 'none'}")
    L.append(f"- rejected, unsigned edge: {len(s['rejected_unsigned'])} "
             f"{', '.join(s['rejected_unsigned']) or 'none'}\n")
    L.append("Targets rejected for want of a resolvable sign are reported rather than")
    L.append("dropped: plan section 0.4 forbids inferring direction from unsigned")
    L.append("proximity, so an unsigned edge is a dead end, not a weak signal.\n")
    L.append("## Directional tractability\n")
    L.append("| target | required | ChEMBL | mechanisms | activating | inhibiting | max phase | verdict |")
    L.append("|---|---|---|---:|---:|---:|---:|---|")
    tot = act = 0
    for n, t in sorted(results, key=lambda r: -r[1].n_mechanisms):
        tot += t.n_mechanisms
        act += t.n_activating
        L.append(f"| {t.gene} | {n.direction.value} | {t.chembl_target_id or 'NA'} | "
                 f"{t.n_mechanisms} | {t.n_activating} | {t.n_inhibiting} | "
                 f"{t.max_phase:g} | {t.status.value} |")
    L.append("")
    L.append("## Result\n")
    L.append(f"**{tot} drug-mechanism records across {len(results)} nominated targets. "
             f"{act} act in the required direction.**\n")
    if act == 0:
        L.append("Every drug that exists for these targets is an inhibitor, antagonist or")
        L.append("blocker. The mechanism requires activation. The direct axis is therefore")
        L.append("not merely unproven; it is pharmacologically unavailable in the direction")
        L.append("the biology demands.\n")
        L.append("This is an empirical confirmation of plan section 7.1, which asserts that")
        L.append("constitutional aneuploidy cannot be fixed with a small molecule. It is")
        L.append("also a safety finding: activating mitotic kinases such as PLK1, AURKB or")
        L.append("CDK1 in a child with a cancer predisposition syndrome would be")
        L.append("contraindicated even if an activator existed.\n")
        L.append("### Consequence\n")
        L.append("Track 2 effort moves to the axes plan section 7.1 already prefers:")
        L.append("proteotoxic stress mitigation, mitochondrial and oxidative support, and")
        L.append("above all cancer chemoprevention and surveillance, which the proband's")
        L.append("rhabdomyosarcoma (HP:0002859) makes the most directly relevant of the")
        L.append("three.\n")
    out.write_text("\n".join(L) + "\n")
    print("\n".join(L[-24:]))
    print(f"\nWritten to {out}")

if __name__ == "__main__":
    main()
