#!/usr/bin/env python3
"""Arm A shortlist: proband variants in the known MVA genes that survive rarity.

Writes results/summaries/arm_a_shortlist.md (aggregate) and
results/arm_a_shortlist.tsv (variant-level, gitignored, for downstream tools).

The variant-level file exists because Arm B needs coordinates to run SpliceAI
and Pangolin on. It stays out of git and out of any LLM context, per CLAUDE.md
rule 1; only the aggregate summary is read by a person or an agent.
"""
from __future__ import annotations
import argparse, collections, csv, pathlib, sys
sys.path.insert(0, "src")

from mva.track1.annotators import GnomadFrequencyAnnotator
from mva.track1.pipeline import (PanelAnnotator, QualityAnnotator, RegionAnnotator,
                                 Track1Pipeline)
from mva.track1.regions import GeneModel

PANEL = "config/gene_panels/mitotic_extended.tsv"
GTF = "refs/Homo_sapiens.GRCh38.115.gtf.gz"
VCF = "data/WGS_EX2312012_HGWCNDSX7.vcf.gz"

ap = argparse.ArgumentParser()
ap.add_argument("--gnomad", default="refs/gnomad_mva_known/panel_af.tsv.gz")
ap.add_argument("--bed", default="config/gene_panels/mva_known.nochr.bed")
ap.add_argument("--out-md", default="results/summaries/arm_a_shortlist.md")
ap.add_argument("--out-tsv", default="results/arm_a_shortlist.tsv")
ap.add_argument("--label", default="the known MVA genes")
args = ap.parse_args()
GNOMAD = args.gnomad

rows = list(csv.DictReader(open(PANEL, newline=""), delimiter="\t"))
core = {r["symbol"] for r in rows if r["in_core_panel"] == "yes"}
gm = GeneModel.from_gtf(GTF, symbols=core)
gn = GnomadFrequencyAnnotator(table=GNOMAD)

pipe = Track1Pipeline(
    gm,
    annotators=[PanelAnnotator(PANEL), RegionAnnotator(gm), QualityAnnotator(), gn],
    panel_tsv=PANEL)
regions = [f"{l.split()[0]}:{l.split()[1]}-{l.split()[2]}" for l in open(args.bed)]
res = pipe.run(VCF, regions=regions)

def is_rare(c):
    crit = {e.criterion for e in c.evidence}
    return "too_common" not in crit and "homozygotes_in_gnomad" not in crit

short = [c for c in res.candidates if is_rare(c)]
short.sort(key=lambda c: -c.score)

# Variant-level output for downstream tools. Gitignored.
out_tsv = pathlib.Path(args.out_tsv)
out_tsv.parent.mkdir(parents=True, exist_ok=True)
with out_tsv.open("w") as fh:
    fh.write("chrom\tpos\tref\talt\tgene\tclass\tzygosity\tscore\tfilter\n")
    for c in short:
        p = c.position
        filt = next((e.detail.get("bcsq", "") for e in c.evidence), "")
        fh.write(f"{p.contig}\t{p.pos}\t{p.ref}\t{p.alt}\t{c.gene}\t"
                 f"{c.variant_class.value}\t{c.zygosity.value}\t{c.score:.2f}\t{filt}\n")

# Aggregate summary. Safe to read.
by_gene = collections.Counter(c.gene for c in short)
by_class = collections.Counter(c.variant_class.value for c in short)
by_zyg = collections.Counter(c.zygosity.value for c in short)
freq = collections.Counter()
for c in res.candidates:
    crit = {e.criterion for e in c.evidence}
    freq["absent" if "absent_from_gnomad" in crit else
         "rare" if "rare_in_gnomad" in crit else
         "common" if "too_common" in crit else "intermediate"] += 1

L = [f"# Arm A shortlist: {args.label} after population filtering\n"]
L.append(f"Generated by `scripts/18_arm_a_shortlist.py`. {res.completeness_note()}\n")
L.append("## The narrowing\n")
L.append(f"| Stage | Variants |")
L.append("|---|---:|")
L.append(f"| Called in {args.label} (plus 5 kb flanks) | {res.n_records_seen} |")
L.append(f"| Mapped to a panel gene and scored | {len(res.candidates)} |")
L.append(f"| **Survive population filtering** | **{len(short)}** |")
L.append("")
L.append("Population frequency distribution of all scored variants:\n")
L.append("| gnomAD v4.1 frequency | n |")
L.append("|---|---:|")
for k in ("absent", "rare", "intermediate", "common"):
    L.append(f"| {k} | {freq[k]} |")
L.append("")
L.append(f"**{freq['common']} of {len(res.candidates)} "
         f"({100*freq['common']/max(1,len(res.candidates)):.0f}%) are common polymorphisms.** "
         "That is the expected shape: the known MVA genes are unconstrained, carriers")
L.append("are healthy, and ordinary population variation fills the gene bodies. The")
L.append("filter is doing its job.\n")
L.append("## What survives\n")
L.append("| gene | shortlisted |")
L.append("|---|---:|")
for g, n in by_gene.most_common():
    L.append(f"| {g} | {n} |")
L.append("")
L.append("| variant class | n | | zygosity | n |")
L.append("|---|---:|---|---|---:|")
cls = list(by_class.most_common()); zyg = list(by_zyg.most_common())
for i in range(max(len(cls), len(zyg))):
    a = f"{cls[i][0]} | {cls[i][1]}" if i < len(cls) else " | "
    b = f"{zyg[i][0]} | {zyg[i][1]}" if i < len(zyg) else " | "
    L.append(f"| {a} | | {b} |")
L.append("")
L.append("## Reading this honestly\n")
L.append("This is a shortlist, not a candidate list. Three things are missing:\n")
L.append("1. **No splicing prediction.** Every shortlisted variant is intronic or")
L.append("   untranslated, which is exactly where a cryptic allele would be and exactly")
L.append("   where nothing can be said without SpliceAI or Pangolin. This shortlist is")
L.append("   the input to Arm B, not its output.")
L.append("2. **No protein consequence**, so any coding variant here is unclassified.")
L.append("3. **No phase.** Physical phasing did not resolve a *trans* pair in any known")
L.append("   MVA gene except CEP192, so we cannot yet say whether any two of these sit")
L.append("   on opposite haplotypes.\n")
L.append("The value of the step is the reduction: a set of "
         f"{len(short)} variants is small enough to run every remaining tool over")
L.append("exhaustively, including tools far too slow for a whole panel.\n")

pathlib.Path("results/summaries").mkdir(parents=True, exist_ok=True)
pathlib.Path(args.out_md).write_text("\n".join(L) + "\n")
print("\n".join(L))
print(f"\nvariant-level shortlist (gitignored): {out_tsv}")
