#!/usr/bin/env python3
"""Adversarial verification of the Track 1 claims against primary sources.

Reads the ORIGINAL callset in data/ (not the VEP output) and the reference
FASTA, and writes an aggregate summary to results/summaries/verification_callset.md.

Per CLAUDE.md rule 1 this script may read data/; its output is restricted to
aggregate counts plus the five candidate loci that are already published in
submission/track1_submission.csv under CC BY 4.0.
"""
from __future__ import annotations
import pathlib, subprocess, sys

VCF = "data/WGS_EX2312012_HGWCNDSX7.vcf.gz"
FASTA = "refs/mva_chroms.fa.gz"          # contigs named without the chr prefix
OUT = pathlib.Path("results/summaries/verification_callset.md")

# Loci already published in the submission. Nothing else is emitted.
LOCI = [
    ("BUB1B allele 1", "15", 40209701, "T", "G"),
    ("BUB1B allele 2", "15", 40220612, "T", "G"),
    ("LZTR1 secondary", "22", 20996720, "C", "G"),
    ("PEX5 excluded",  "12", 7190512,  None, None),
    ("CTU2 excluded",  "16", 88714226, None, None),
]
BUB1B_REGION = "15:40155984-40226137"    # config/gene_panels/mva_known.tsv, 5 kb flanks


def sh(cmd: str) -> str:
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, check=True).stdout


def contig_counts(path: str) -> dict[str, int]:
    """Per-contig record counts, streamed.

    The shipped .tbi carries no count metadata, so `bcftools index -n` returns
    zero on it. Streaming is the only trustworthy count here.
    """
    counts: dict[str, int] = {}
    proc = subprocess.Popen(["bcftools", "query", "-f", "%CHROM\n", path],
                            stdout=subprocess.PIPE, text=True)
    assert proc.stdout is not None
    for line in proc.stdout:
        c = line.rstrip("\n")
        counts[c] = counts.get(c, 0) + 1
    proc.wait()
    return counts


out: list[str] = []
w = out.append
w("# Verification of the Track 1 claims against the original callset\n")
w("Generated by `scripts/25_verify_track1_claims.py`. Aggregate counts plus the "
  "five loci already published in `submission/track1_submission.csv`.\n")

# ---------------------------------------------------------------- record count
callset_contigs = contig_counts(VCF)
n_records = sum(callset_contigs.values())
w("## 1. Callset record count\n")
w(f"| claimed | 5,012,204 |\n|---|---|\n| observed | {n_records:,} |\n"
  f"| agrees | {'YES' if n_records == 5012204 else 'NO'} |\n")

# ---------------------------------------------------------------------- loci
w("\n## 2. The candidate loci, read from the original callset\n")
w("| locus | CHROM:POS | REF | ALT | FILTER | GT | DP | AD | GQ | PGT | PID |")
w("|---|---|---|---|---|---|---|---|---|---|---|")
found = {}
for name, chrom, pos, exp_ref, exp_alt in LOCI:
    q = sh(f"bcftools query -r {chrom}:{pos}-{pos} "
           f"-f '%CHROM\\t%POS\\t%REF\\t%ALT\\t%FILTER\\t[%GT\\t%DP\\t%AD\\t%GQ\\t%PGT\\t%PID]\\n' {VCF}")
    if not q.strip():
        w(f"| {name} | {chrom}:{pos} | ABSENT FROM CALLSET |||||||||")
        found[name] = None
        continue
    for line in q.strip().split("\n"):
        f = line.split("\t")
        found[name] = f
        w("| " + name + " | " + f"{f[0]}:{f[1]}" + " | " + " | ".join(f[2:]) + " |")

w("\n### REF and ALT against what the submission claims\n")
w("| locus | claimed | observed | agrees |")
w("|---|---|---|---|")
for name, chrom, pos, exp_ref, exp_alt in LOCI:
    if exp_ref is None:
        continue
    f = found.get(name)
    obs = f"{f[2]}>{f[3]}" if f else "absent"
    w(f"| {name} | {exp_ref}>{exp_alt} | {obs} | "
      f"{'YES' if f and f[2] == exp_ref and f[3] == exp_alt else 'NO'} |")

# ------------------------------------------------------- reference base check
w("\n## 3. REF alleles against the GRCh38 reference FASTA\n")
w(f"Source: `{FASTA}` (Ensembl 115 primary assembly, no-chr contig naming).\n")
w("| locus | reference base | claimed REF | agrees |")
w("|---|---|---|---|")
for name, chrom, pos, exp_ref, exp_alt in LOCI:
    if exp_ref is None or chrom not in {"15", "10", "18", "2", "6", "9"}:
        continue
    seq = sh(f"samtools faidx {FASTA} {chrom}:{pos}-{pos}").strip().split("\n")[1].upper()
    w(f"| {name} | {seq} | {exp_ref} | {'YES' if seq == exp_ref else 'NO'} |")

# ----------------------------------------------------------------- separation
w("\n## 4. Separation of the two BUB1B alleles\n")
d = 40220612 - 40209701
w(f"40220612 - 40209701 = **{d:,} bp**. Claimed 10,911 bp. "
  f"{'Agrees.' if d == 10911 else 'DOES NOT AGREE.'}\n")

# -------------------------------------------------------------------- phasing
w("\n## 5. PGT/PID physical phasing across BUB1B\n")
q = sh(f"bcftools query -r {BUB1B_REGION} -f '[%PGT\\t%PID]\\n' {VCF}")
lines = [l for l in q.strip().split("\n") if l.strip()]
n_tot = len(lines)
n_phased = sum(1 for l in lines if l.split("\t")[1] not in {".", ""})
pids = sorted({l.split("\t")[1] for l in lines if l.split("\t")[1] not in {".", ""}})
w(f"| records in {BUB1B_REGION} | {n_tot} |\n|---|---|\n"
  f"| records carrying a PID phasing group | {n_phased} |\n"
  f"| distinct phasing groups | {len(pids)} |\n")
if pids:
    w(f"\nPhasing groups present: {', '.join(pids)}\n")
else:
    w("\nNo phasing group anywhere in BUB1B. The claim that PGT/PID reports no "
      "phasing group in this gene is confirmed.\n")

# ------------------------------------------------- per-contig counts for VEP diff
w("\n## 6. Callset versus VEP-annotated record counts\n")
vep = "node_artefacts/all.vep.vcf.gz"
if pathlib.Path(vep).exists():
    vep_contigs = contig_counts(vep)
    n_vep = sum(vep_contigs.values())
    w(f"| callset records | {n_records:,} |\n|---|---|\n"
      f"| VEP-annotated records | {n_vep:,} |\n"
      f"| difference | {n_records - n_vep:,} |\n"
      f"| claimed difference | 61,921 |\n")
    a, b = callset_contigs, vep_contigs
    PRIMARY = {str(i) for i in range(1, 23)} | {"X", "Y", "MT"}
    lost_primary = {k: a[k] - b.get(k, 0) for k in a if k in PRIMARY and a[k] != b.get(k, 0)}
    lost_other = sum(a[k] - b.get(k, 0) for k in a if k not in PRIMARY)
    w(f"\n| records lost on primary contigs (1-22, X, Y, MT) | {sum(lost_primary.values()):,} |\n|---|---|\n"
      f"| records lost on decoy and unplaced contigs | {lost_other:,} |\n")
    if lost_primary:
        w("\n**Primary-contig losses, which the claim says should be zero:**\n")
        w("| contig | callset | VEP | lost |")
        w("|---|---:|---:|---:|")
        for k, v in sorted(lost_primary.items(), key=lambda kv: -kv[1]):
            w(f"| {k} | {a[k]:,} | {b.get(k, 0):,} | {v:,} |")
    else:
        w("\nEvery lost record is on a decoy or unplaced contig. The claim holds.\n")
else:
    w("VEP artefact not present; skipped.\n")

OUT.write_text("\n".join(out) + "\n")
print(f"wrote {OUT}")
