#!/usr/bin/env python3
"""Independent recomputation of the read-level figures in
results/summaries/arm_c_readlevel_verification.md, from the panel BAM.

Reads node_artefacts/WGS_EX2312012.panel.bam; writes an aggregate summary to
results/summaries/verification_readlevel.md. Only the five loci already
published in submission/track1_submission.csv are reported.
"""
from __future__ import annotations
import collections, pathlib, re, subprocess

BAM = "node_artefacts/WGS_EX2312012.panel.bam"
OUT = pathlib.Path("results/summaries/verification_readlevel.md")

LOCI = [
    ("BUB1B allele 1 p.Leu737Ter", "15", 40209701, "G"),
    ("BUB1B allele 2 p.Asn1002Lys", "15", 40220612, "G"),
    ("LZTR1 p.Tyr748Ter", "22", 20996720, "G"),
    ("PEX5 deletion call", "12", 7190512, None),
    ("CTU2 deletion call", "16", 88714226, None),
]

CLAIMED = {   # from results/summaries/arm_c_readlevel_verification.md
    "BUB1B allele 1 p.Leu737Ter":  dict(depth=47, ref=21, alt=26, vaf=0.553, fwd=15, rev=12, mapq=60.0),
    "BUB1B allele 2 p.Asn1002Lys": dict(depth=27, ref=15, alt=12, vaf=0.444, fwd=6,  rev=10, mapq=60.0),
}

BASE_RE = re.compile(r"[ACGTNacgtn]")


def pileup(chrom: str, pos: int, mapq: int = 20, baseq: int = 20):
    """One pileup column with per-base mapping qualities. No reference is passed,
    so mpileup emits the literal read base for every read rather than . and ,."""
    cmd = ["samtools", "mpileup", "-a", "-x", "-B", "-d", "8000",
           "-q", str(mapq), "-Q", str(baseq), "--output-MQ",
           "-r", f"{chrom}:{pos}-{pos}", BAM]
    r = subprocess.run(cmd, capture_output=True, text=True, check=True)
    line = r.stdout.strip().split("\n")[0]
    f = line.split("\t")
    return int(f[3]), f[4], f[6]


def parse(bases: str, mqs: str):
    """Walk the pileup base string, keeping each base aligned to its MAPQ char."""
    counts = collections.Counter()
    strand = collections.defaultdict(lambda: [0, 0])   # base -> [fwd, rev]
    mapq_of = collections.defaultdict(list)
    indel_starts = 0
    i = j = 0
    while i < len(bases):
        c = bases[i]
        if c == "^":        # read start, next char is the mapping quality
            i += 2
            continue
        if c == "$":
            i += 1
            continue
        if c in "+-":       # indel attached to the PREVIOUS base
            m = re.match(r"[+-](\d+)", bases[i:])
            n = int(m.group(1))
            indel_starts += 1
            i += 1 + len(m.group(1)) + n
            continue
        if c in "*#":       # deletion placeholder, consumes an MQ char
            counts["DEL"] += 1
            j += 1
            i += 1
            continue
        if BASE_RE.match(c):
            up = c.upper()
            counts[up] += 1
            strand[up][0 if c.isupper() else 1] += 1
            if j < len(mqs):
                mapq_of[up].append(ord(mqs[j]) - 33)
            j += 1
            i += 1
            continue
        i += 1
    return counts, strand, mapq_of, indel_starts


out: list[str] = []
w = out.append
w("# Independent recomputation of the read-level figures\n")
w("Generated by `scripts/26_verify_readlevel.py` from "
  "`node_artefacts/WGS_EX2312012.panel.bam`, filters MAPQ>=20 and BQ>=20, "
  "the same thresholds the original summary states.\n")

w("## 1. The three reported variant loci\n")
w("| locus | depth | ref reads | alt reads | VAF | alt fwd/rev | mean MAPQ of alt |")
w("|---|---:|---:|---:|---:|---|---:|")
observed = {}
for name, chrom, pos, alt in LOCI:
    if alt is None:
        continue
    depth, bases, mqs = pileup(chrom, pos, 20, 20)
    counts, strand, mapq_of, _ = parse(bases, mqs)
    total = sum(v for k, v in counts.items() if k in "ACGT")
    n_alt = counts[alt]
    n_ref = total - n_alt
    vaf = n_alt / total if total else 0.0
    mq = sum(mapq_of[alt]) / len(mapq_of[alt]) if mapq_of[alt] else float("nan")
    observed[name] = dict(depth=total, ref=n_ref, alt=n_alt, vaf=vaf,
                          fwd=strand[alt][0], rev=strand[alt][1], mapq=mq)
    w(f"| {name} | {total} | {n_ref} | {n_alt} | {vaf:.3f} | "
      f"{strand[alt][0]} fwd / {strand[alt][1]} rev | {mq:.1f} |")

w("\n### Against the figures claimed in `arm_c_readlevel_verification.md`\n")
w("| locus | field | claimed | observed | agrees |")
w("|---|---|---|---|---|")
for name, claim in CLAIMED.items():
    o = observed[name]
    for k in ("depth", "ref", "alt", "vaf", "fwd", "rev", "mapq"):
        cv, ov = claim[k], o[k]
        ok = abs(cv - ov) <= (0.01 if isinstance(cv, float) else 0)
        w(f"| {name} | {k} | {cv} | {ov if isinstance(ov, int) else round(ov, 3)} | "
          f"{'YES' if ok else 'NO'} |")

# ---------------------------------------------------------------- PEX5 / CTU2
w("\n## 2. The two excluded homozygous calls\n")
w("Both are deletion calls in the callset, not substitutions:\n")
w("- `PEX5` 12:7190512 `GGCCTCTGAGGCAGTGAGTGTTCTTGAGGTGGAAAGCCCAGGTGCA` > `G`, "
  "a 45 bp deletion, GT 1/1, DP 10, AD 0,10, GQ 37\n")
w("- `CTU2` 16:88714226 `AGGTGTG` > `A`, a 6 bp deletion, GT 1/1, DP 27, AD 0,27, GQ 82\n")
w("\n| locus | depth (MAPQ>=20) | reads spanning as deletion | reads carrying an indel | mean MAPQ |")
w("|---|---:|---:|---:|---:|")
for name, chrom, pos, alt in LOCI:
    if alt is not None:
        continue
    depth, bases, mqs = pileup(chrom, pos, 20, 0)
    counts, strand, mapq_of, indels = parse(bases, mqs)
    total = sum(v for k, v in counts.items() if k in "ACGT")
    allmq = [q for v in mapq_of.values() for q in v]
    mq = sum(allmq) / len(allmq) if allmq else float("nan")
    w(f"| {name} | {total + counts['DEL']} | {counts['DEL']} | {indels} | {mq:.1f} |")

w("\nAt MAPQ 0 (no mapping-quality filter), for comparison:\n")
w("| locus | depth | reads spanning as deletion | reads carrying an indel | MAPQ-0 reads |")
w("|---|---:|---:|---:|---:|")
for name, chrom, pos, alt in LOCI:
    if alt is not None:
        continue
    d0, b0, m0 = pileup(chrom, pos, 0, 0)
    c0, s0, mq0, ind0 = parse(b0, m0)
    t0 = sum(v for k, v in c0.items() if k in "ACGT")
    zero = sum(1 for v in mq0.values() for q in v if q == 0)
    w(f"| {name} | {t0 + c0['DEL']} | {c0['DEL']} | {ind0} | {zero} |")

OUT.write_text("\n".join(out) + "\n")
print(f"wrote {OUT}")
