#!/usr/bin/env python3
"""Track 2, chemoprevention axis: derive candidates from the registry and screen them.

Plan section 7.1 ranks cancer chemoprevention and surveillance as the
highest-value output of Track 2. This script builds that axis end to end and
writes results/summaries/track2_chemoprevention.md.

It answers three questions in order, and the first two are answered "nothing":

1. What chemoprevention evidence exists for this proband's actual disease and
   actual tumour? Queried directly. The answer is none, and that is the finding
   that shapes everything after it.
2. So what is the nearest evidence base? Prevention trials in hereditary cancer
   predisposition syndromes, anchored on the registry's own MeSH heading rather
   than on a list of syndromes we chose.
3. Of the agents in it, which survive a deterministic contraindication screen
   for a child with a chromosomal instability syndrome and a cancer
   predisposition?

Nothing here is a treatment recommendation. See CLAUDE.md rule 3 and ETHICS.md
section 4.
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, "src")

from mva.track2.chemoprevention import (
    MESH_HEREDITARY_NEOPLASTIC,
    ChemblMolecule,
    count_trials,
    endpoint_classes,
    extract_drug_agents,
    mechanism_actions,
    paediatric_trials,
    query_trials,
    resolve_molecule,
)
from mva.track2.safety import DrugRecord, Verdict, screen

ATC_TABLE = pathlib.Path("refs/atc/atc_l01.json")



def control_agents(n: int = 5) -> list[str]:
    """Known cytotoxic agents, named by the WHO ATC table rather than by us.

    Taken from L01A, the alkylating-agent subgroup, whose members are cytotoxic
    by definition of the class. Used as a negative control on the safety screen.
    """
    import json
    if not ATC_TABLE.exists():
        return []
    rows = json.loads(ATC_TABLE.read_text()).get("atc", [])
    names = [r["who_name"] for r in rows
             if r.get("level3") == "L01A" and r.get("who_name")]
    return sorted(names)[:n]

CACHE = pathlib.Path("results/track2/cache")
OUT = pathlib.Path("results/summaries/track2_chemoprevention.md")

#: The proband's own disease and tumour. Queried to establish that the
#: syndrome-specific evidence base is empty, which is a reported negative and
#: the premise of the transfer argument.
PROBAND_QUERIES = {
    "any trial in mosaic variegated aneuploidy":
        'AREA[ConditionSearch]"Mosaic Variegated Aneuploidy"',
    "any trial naming BUB1B":
        'AREA[ConditionSearch]"BUB1B" OR AREA[InterventionName]"BUB1B"',
    "prevention trial in rhabdomyosarcoma":
        'AREA[ConditionSearch]"Rhabdomyosarcoma" AND AREA[DesignPrimaryPurpose]PREVENTION',
    "prevention trial with a drug, in rhabdomyosarcoma":
        'AREA[ConditionSearch]"Rhabdomyosarcoma" AND AREA[DesignPrimaryPurpose]PREVENTION '
        'AND AREA[InterventionType]DRUG',
}

DERIVATION = (f'AREA[ConditionSearch]"{MESH_HEREDITARY_NEOPLASTIC}" '
              f'AND AREA[DesignPrimaryPurpose]PREVENTION '
              f'AND AREA[InterventionType]DRUG')


def main() -> None:
    L: list[str] = []
    w = L.append

    w("# Track 2: cancer chemoprevention and surveillance\n")
    w("Generated by `scripts/27_track2_chemoprevention.py`. Sources: "
      "ClinicalTrials.gov API v2, ChEMBL, and the deterministic safety screen in "
      "`src/mva/track2/safety.py`.\n")
    w("Every agent below is derived from a registry query and every identifier is "
      "returned by an API call. Nothing here is a treatment recommendation, no "
      "dose appears anywhere, and none of this is addressed to a clinician "
      "treating this child. See `CLAUDE.md` rule 3.\n")

    # ---------------------------------------------------------------- stage 0
    w("## 1. The evidence base for this proband is empty\n")
    w("Asked first, because the answer determines what the rest of the axis can "
      "honestly claim.\n")
    w("| Question | Trials found |")
    w("|---|---:|")
    empties = 0
    for label, expr in PROBAND_QUERIES.items():
        n = count_trials(expr, CACHE)
        empties += (n == 0)
        w(f"| {label} | **{n}** |")
    w("")
    w("**There is no chemoprevention evidence base for mosaic variegated "
      "aneuploidy, and none for rhabdomyosarcoma.** Not a thin one. An empty "
      "one. No interventional trial in the registry has this proband's disease "
      "as a condition, and no prevention trial of any kind has their tumour.\n")
    w("This is the single most important fact about the axis and it is reported "
      "first rather than buried. Every candidate below is transferred from a "
      "different syndrome with a different driver gene and a different tumour "
      "spectrum. That transfer is an assumption, it is doing most of the work, "
      "and no amount of downstream filtering repairs it.\n")

    # ---------------------------------------------------------------- stage 1
    w("## 2. Candidate derivation\n")
    w(f"Anchored on the registry's own MeSH heading **\"{MESH_HEREDITARY_NEOPLASTIC}\"** "
      "rather than on a list of syndrome names chosen by us. A list we chose "
      "would be a statement about what an author recalled; the heading makes it "
      "a statement about what the registry holds, and it is reproducible by "
      "anyone running the same query.\n")
    w("```")
    w(DERIVATION)
    w("```\n")

    total = count_trials(DERIVATION, CACHE)
    studies = query_trials(DERIVATION, CACHE) or {}
    agents = extract_drug_agents(studies)
    w(f"- prevention trials with a drug intervention in hereditary cancer "
      f"predisposition: **{total}**")
    w(f"- distinct agent names after dose and formulation text is stripped: "
      f"**{len(agents)}**\n")
    w("Intervention names are sponsor free text and routinely embed doses, so "
      "`strip_dose` removes them before any name is emitted and combination arms "
      "are split into their components. A test asserts that no output of this "
      "axis carries a dose pattern.\n")

    # ---------------------------------------------------------------- stage 2
    resolved: list[tuple[str, ChemblMolecule, object]] = []
    unresolved: list[str] = []
    for key in sorted(agents):
        ev = agents[key]
        mol = resolve_molecule(ev.agent, CACHE)
        if mol is None:
            unresolved.append(ev.agent)
            continue
        resolved.append((ev.agent, mol, ev))

    w("## 3. Resolution to ChEMBL\n")
    w(f"| resolved to a ChEMBL molecule | **{len(resolved)}** |")
    w("|---|---:|")
    w(f"| unresolved, reported as a gap | {len(unresolved)} |\n")
    w("A name resolves only when it matches a ChEMBL preferred name or synonym "
      "exactly. Fuzzy search returns a nearest molecule for almost anything, and "
      "a plausible wrong ChEMBL identifier in a report is worse than a gap "
      "because a reader cannot tell it is wrong (`CLAUDE.md` rule 2).\n")
    if unresolved:
        w("Unresolved names, left as gaps rather than guessed at: "
          + ", ".join(f"`{u}`" for u in sorted(unresolved)[:25])
          + (" ..." if len(unresolved) > 25 else "") + "\n")

    # ------------------------------------------------------------ stages 3, 4
    rows = []
    for agent, mol, ev in resolved:
        acts = mechanism_actions(mol.chembl_id, CACHE)
        paeds = paediatric_trials(agent, CACHE)
        rec = DrugRecord(
            name=mol.pref_name,
            chembl_id=mol.chembl_id,
            atc_codes=mol.atc_codes,
            mechanism="; ".join(acts) or None,
            paediatric_trial_ids=paeds,
            # The lookup ran either way. False, not None, when it came back
            # empty: "we looked and found nothing" is a different statement from
            # "we did not look", and the screen distinguishes them.
            has_paediatric_pk=bool(paeds),
            provenance=f"ChEMBL {mol.chembl_id}; ClinicalTrials.gov",
        )
        rows.append((agent, mol, ev, rec, screen(rec)))

    order = {Verdict.ALLOWED: 0, Verdict.FLAGGED: 1, Verdict.UNKNOWN: 2, Verdict.EXCLUDED: 3}
    rows.sort(key=lambda r: (order[r[4].verdict], -r[2].n_trials, r[1].pref_name))

    counts = {v: sum(1 for r in rows if r[4].verdict is v) for v in Verdict}
    w("## 4. The safety screen\n")
    w("Deterministic rules over structured drug fields, per plan section 7.4 and "
      "`CLAUDE.md` rule 3. No model judgement enters a verdict. Every verdict "
      "names the rule that produced it and the field that rule read.\n")
    w("| verdict | agents |")
    w("|---|---:|")
    for v in (Verdict.ALLOWED, Verdict.FLAGGED, Verdict.UNKNOWN, Verdict.EXCLUDED):
        w(f"| {v.value} | {counts[v]} |")
    w("")
    w("`UNKNOWN` is not a soft pass. It means the paediatric exposure evidence "
      "required by plan section 7.4 was not found, and an agent carrying it must "
      "never be presented as though paediatric use were established.\n")

    w("## 5. Candidates, with their caveats attached\n")
    w("Ordered by screen verdict, then by how much registry evidence stands "
      "behind the agent. This is a prioritisation for research evaluation, not a "
      "ranking of clinical preference.\n")
    w("| agent | ChEMBL | max phase | ATC | prevention trials | paediatric trials | verdict |")
    w("|---|---|---:|---|---:|---:|---|")
    for _agent, mol, ev, rec, res in rows:
        atc = ", ".join(mol.atc_codes[:3]) or "none"
        if mol.atc_inherited_from:
            atc += f" (from parent {mol.atc_inherited_from})"
        mp = f"{mol.max_phase:g}" if mol.max_phase is not None else "n/a"
        w(f"| {mol.pref_name} | {mol.chembl_id} | {mp} | {atc} | {ev.n_trials} | "
          f"{len(rec.paediatric_trial_ids)} | **{res.verdict.value}** |")
    w("")
    inh = [m for _, m, _, _, _ in rows if m.atc_inherited_from]
    if inh:
        w(f"{len(inh)} agent(s) are salt or ester forms carrying no ATC code of "
          f"their own, so their codes are inherited from the ChEMBL parent "
          f"molecule. Without that step the screen flags a base and silently "
          f"passes its own hydrochloride, which is the same active molecule and "
          f"the same concern.\n")

    w("### Caveats that must travel with each candidate\n")
    any_caveat = False
    for _agent, mol, ev, rec, res in rows:
        if res.verdict is Verdict.EXCLUDED or not res.mandatory_caveats:
            continue
        any_caveat = True
        w(f"**{mol.pref_name}** (`{mol.chembl_id}`)")
        for c in res.mandatory_caveats:
            w(f"- {c}")
        if rec.paediatric_trial_ids:
            w(f"- paediatric exposure evidence: "
              f"{', '.join(rec.paediatric_trial_ids)}")
        w(f"- registry support: {ev.n_trials} prevention trial(s), "
          f"{', '.join(ev.nct_ids[:4])}"
          + (" ..." if len(ev.nct_ids) > 4 else ""))
        w("")
    if not any_caveat:
        w("No candidate carries a caveat, which would itself be suspicious.\n")

    # ---------------------------------------------------- endpoint scope
    w("### What each trial actually measured\n")
    w("The registry's `PREVENTION` purpose covers prevention of any endpoint, "
      "not only of cancer, and a trial's condition list does not say what it "
      "measured. A trial in a hereditary cancer syndrome may have counted new "
      "lesions, or measured Ki-67 staining, or counted seizures. Only the first "
      "is evidence about tumour prevention, and treating the three as "
      "interchangeable is how a chemoprevention list acquires agents that were "
      "never tested against a tumour.\n")
    w("Each agent's primary outcome text is classified below, and the text is "
      "printed beside the classification so a reader can overrule it. The "
      "keyword sets are ours, in `src/mva/track2/chemoprevention.py`, not "
      "registry fields.\n")
    w("| agent | endpoint classes | primary outcome, as recorded |")
    w("|---|---|---|")
    n_tumour = 0
    for _agent, mol, ev, _rec2, _res2 in rows:
        if _res2.verdict is Verdict.EXCLUDED:
            continue
        cls = endpoint_classes(ev)
        n_tumour += "tumour" in cls
        sample = ev.outcomes[0] if ev.outcomes else "none recorded"
        if len(sample) > 110:
            sample = sample[:107] + "..."
        w(f"| {mol.pref_name} | {', '.join(sorted(cls))} | {sample} |")
    w("")
    w(f"**{n_tumour} of {len(rows)} agents** have at least one primary outcome "
      f"that counts tumours or lesions. The rest reached this list through a "
      f"surrogate endpoint or an endpoint unrelated to cancer, and are weaker "
      f"candidates for that reason rather than stronger ones. They are shown "
      f"rather than filtered out, because the filter would be our judgement and "
      f"a reader is entitled to apply their own.\n")

    # ------------------------------------------------------------ control
    w("### Negative control: does the screen exclude anything at all?\n")
    w("A screen that excludes nothing may be permissive or may be broken, and "
      "the candidate set cannot tell you which, because prevention trials rarely "
      "test cytotoxics. So known cytotoxic agents are pushed through the "
      "identical code path: resolved against ChEMBL by name, screened by the "
      "same rules. Their names are taken from the WHO ATC L01A alkylating-agent "
      "subgroup as cached in `refs/atc/atc_l01.json`, not chosen by us.\n")
    controls = control_agents()
    w("| control agent | ChEMBL | ATC | verdict | rule |")
    w("|---|---|---|---|---|")
    n_ctrl_excluded = 0
    for cname in controls:
        cmol = resolve_molecule(cname, CACHE)
        if cmol is None:
            w(f"| {cname} | unresolved | | | |")
            continue
        crec = DrugRecord(name=cmol.pref_name, chembl_id=cmol.chembl_id,
                          atc_codes=cmol.atc_codes,
                          mechanism="; ".join(mechanism_actions(cmol.chembl_id, CACHE)) or None,
                          provenance=f"ChEMBL {cmol.chembl_id}")
        cres = screen(crec)
        n_ctrl_excluded += cres.verdict is Verdict.EXCLUDED
        rule = next((f.rule_id for f in cres.findings if f.verdict is Verdict.EXCLUDED), "-")
        w(f"| {cmol.pref_name} | {cmol.chembl_id} | "
          f"{', '.join(cmol.atc_codes[:2]) or 'none'} | "
          f"**{cres.verdict.value}** | {rule} |")
    w("")
    w(f"**{n_ctrl_excluded} of {len(controls)} controls excluded.** "
      + ("The screen discriminates, so an empty exclusion list above is a "
         "property of the candidate set rather than of the screen.\n"
         if n_ctrl_excluded == len(controls) else
         "**Not all controls were excluded. The screen is not trustworthy until "
         "this is fixed, and no verdict above should be relied on.**\n"))

    w("### Excluded, and why\n")
    excl = [r for r in rows if r[4].verdict is Verdict.EXCLUDED]
    if excl:
        w("| agent | ChEMBL | rule | reason |")
        w("|---|---|---|---|")
        for _agent, mol, _ev, _rec, res in excl:
            for f in res.findings:
                if f.verdict is Verdict.EXCLUDED:
                    w(f"| {mol.pref_name} | {mol.chembl_id} | {f.rule_id} | {f.reason} |")
    else:
        w("Nothing was excluded, which is worth checking rather than celebrating.\n")
    w("")

    w("## 6. What this axis does and does not establish\n")
    w("**Establishes.** That the chemoprevention evidence base for this "
      "proband's disease and tumour is empty; that a transferable evidence base "
      "exists in other hereditary cancer predisposition syndromes and what is in "
      "it; and which of those agents survive a contraindication screen written "
      "for this specific biology, with the reason recorded per agent.\n")
    w("**Does not establish.** That any agent here would reduce tumour incidence "
      "in mosaic variegated aneuploidy. There is no evidence for that "
      "proposition and this analysis does not create any. The tumour biology of "
      "`BUB1B`-related MVA is chromosomal missegregation, which is not the "
      "mechanism any of these agents was developed against.\n")
    w("**What would falsify the axis.** A chemoprevention agent that works "
      "through a mechanism specific to the driver of its own syndrome, and not "
      "through a general anti-tumour-initiation route, should not transfer. The "
      "experiment that would tell us is a tumour-incidence study in a "
      "`Bub1b` hypomorphic mouse, which is the standard model for this disease. "
      "Until something of that kind exists, every candidate here is a hypothesis "
      "about where to look, not a finding.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L[:40]))
    print(f"\n... written to {OUT}")


if __name__ == "__main__":
    main()
