#!/usr/bin/env python3
"""Is each Track 2 axis available in the direction its biology requires?

Plan section 7.1 lists three axes that survive the fact that constitutional
aneuploidy cannot be fixed with a small molecule. This script asks the same
question of all three, and of the closed direct axis as a control, using one
instrument: what fraction of an axis's genes has any drug that pushes it the way
the biology needs?

Why the control matters more than the result
--------------------------------------------
The project's headline Track 2 finding is that the direct spindle-checkpoint
axis yields ten targets, all requiring activation, with 118 ChEMBL mechanism
records between them and none activating. Stated alone that sounds like a
property of this axis. It may instead be a property of pharmacology: activating
drugs are rare everywhere. This script measures the base rate so the claim can
be stated at the strength the evidence actually supports, which is the point of
running it.

Writes results/summaries/track2_axis_availability.md.
"""
from __future__ import annotations

import csv
import pathlib
import sys

sys.path.insert(0, "src")

from mva.track2.druggable_direction import (binom_zero, build_directional_proteome,
                                            go_gene_symbols, resolve_go_term)
from mva.track2.targets import Direction, fetch_signed_edges, nominate

CACHE = "results/track2/cache_dd"
OUT = pathlib.Path("results/summaries/track2_axis_availability.md")
HGNC = pathlib.Path("refs/hgnc_complete_set.txt")

SEEDS = {"BUB1B", "CEP57", "TRIP13", "BUB1", "BUB3", "CEP192", "SMC5", "CENATAC"}

#: Each axis, its required direction, and the GO term names it is defined by.
#: Term names are resolved to identifiers through QuickGO by exact name match,
#: never written down from memory (CLAUDE.md rule 2).
AXES = [
    ("Proteotoxic stress mitigation", Direction.ACTIVATE,
     ["cellular response to unfolded protein", "macroautophagy",
      "protein folding chaperone"]),
    ("Mitochondrial and oxidative support", Direction.ACTIVATE,
     ["cellular response to oxidative stress",
      "mitochondrial respiratory chain complex assembly", "aerobic respiration"]),
]


def n_protein_coding() -> int:
    if not HGNC.exists():
        return 0
    n = 0
    with HGNC.open(newline="") as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            if r.get("locus_group") == "protein-coding gene" and r.get("status") == "Approved":
                n += 1
    return n


def main() -> None:
    L: list[str] = []
    w = L.append

    prot = build_directional_proteome(CACHE)
    n_genes = n_protein_coding()
    act_rate = len(prot.activatable) / n_genes if n_genes else 0.0
    inh_rate = len(prot.inhibitable) / n_genes if n_genes else 0.0

    w("# Track 2: directional availability of each therapeutic axis\n")
    w("Generated by `scripts/28_track2_axis_availability.py`. Sources: ChEMBL "
      "drug mechanisms, QuickGO annotations, HGNC.\n")

    w("## 1. The base rate, measured before any claim is made about an axis\n")
    w("Every axis that survives plan section 7.1 requires *increasing* the "
      "activity of something. Before concluding that any particular axis is "
      "closed, it is worth knowing how often activation is available at all.\n")
    w("| | genes | share of protein-coding genome |")
    w("|---|---:|---:|")
    w(f"| have an **activating** drug mechanism in ChEMBL | {len(prot.activatable):,} | "
      f"{act_rate:.2%} |")
    w(f"| have an **inhibiting** drug mechanism in ChEMBL | {len(prot.inhibitable):,} | "
      f"{inh_rate:.2%} |")
    w(f"| approved protein-coding genes (HGNC) | {n_genes:,} | |")
    w("")
    w(f"Built from {prot.n_activating_mechanisms:,} activating and "
      f"{prot.n_inhibiting_mechanisms:,} inhibiting mechanism records.\n")
    w(f"**Inhibition is roughly {inh_rate / act_rate:.1f} times more available "
      f"than activation.** That asymmetry is the background against which every "
      f"result below has to be read, and it is measured here rather than "
      f"assumed.\n")

    # ------------------------------------------------------------- control
    w("## 2. The direct axis, re-examined against that base rate\n")
    edges = fetch_signed_edges(sorted(SEEDS))
    partners: dict[str, list] = {}
    for es in edges.values():
        for e in es:
            if e.target in SEEDS and e.source not in SEEDS:
                partners.setdefault(e.source, []).append(e)
    noms = [nominate(g, es, SEEDS) for g, es in partners.items()]
    direct = [n.gene for n in noms if n.is_nominable and n.direction is Direction.ACTIVATE]
    hits = [g for g in direct if g in prot.activatable]
    p0 = binom_zero(act_rate, len(direct))

    w(f"The direction audit nominates **{len(direct)}** targets, every one "
      f"requiring activation: {', '.join(sorted(direct))}.\n")
    w(f"- with an activating drug in ChEMBL: **{len(hits)}**")
    w(f"- expected under the genome-wide activation rate: "
      f"**{act_rate * len(direct):.2f}**")
    w(f"- probability of observing zero at that rate: **{p0:.2f}**\n")
    w("**This weakens the claim, and the weakened version is the one we make.** "
      "Finding no activator across ten targets is what the base rate predicts. "
      "It is not evidence that these targets are unusually undruggable, and "
      "presenting it that way would be reading a general property of "
      "pharmacology as a discovery about the spindle assembly checkpoint.\n")
    w("What survives is narrower and still worth reporting:\n")
    w("1. **The axis is unavailable in fact.** No activating drug exists for any "
      "of these targets today, whatever the reason. A repurposing proposal "
      "aimed at them has nothing to repurpose.")
    w("2. **Every nominated target requires activation, and none requires "
      "inhibition.** An axis with a mix would have the more available direction "
      "open to it. This one does not.")
    w("3. **The safety argument is independent of availability.** Activating "
      "mitotic kinases in a child with a cancer predisposition syndrome would "
      "be contraindicated if an activator existed, so the axis stays closed "
      "even if one is developed.\n")
    inh_open = [g for g in direct if g in prot.inhibitable]
    w(f"For contrast, **{len(inh_open)} of {len(direct)}** of the same targets "
      f"have an inhibiting drug: {', '.join(sorted(inh_open))}. The wrong "
      f"direction is well supplied.\n")

    # --------------------------------------------------------------- axes
    w("## 3. The remaining axes\n")
    w("Each axis is defined by GO terms resolved through QuickGO by exact name "
      "match. Annotations are counted twice: over all evidence codes, and over "
      "experimental codes only, because electronically inferred annotations "
      "dominate large GO terms and inflate a gene set without adding evidence.\n")

    for name, direction, terms in AXES:
        ids = {t: resolve_go_term(t, CACHE) for t in terms}
        w(f"### {name}\n")
        w(f"Required direction: **{direction.value}**.\n")
        w("| GO term | identifier | genes, all evidence | genes, experimental only |")
        w("|---|---|---:|---:|")
        allg: set[str] = set()
        expg: set[str] = set()
        for t, gid in ids.items():
            if gid is None:
                w(f"| {t} | **unresolved** | | |")
                continue
            a = go_gene_symbols(gid, CACHE, experimental_only=False)
            e = go_gene_symbols(gid, CACHE, experimental_only=True)
            allg |= a
            expg |= e
            w(f"| {t} | {gid} | {len(a):,} | {len(e):,} |")
        w("")
        want = prot.activatable if direction is Direction.ACTIVATE else prot.inhibitable
        other = prot.inhibitable if direction is Direction.ACTIVATE else prot.activatable
        hit = sorted(allg & set(want))
        hit_e = sorted(expg & set(want))
        wrong = sorted(allg & set(other))
        exp = act_rate * len(allg) if direction is Direction.ACTIVATE else inh_rate * len(allg)
        w(f"| | genes | with a drug in the required direction | expected at base rate |")
        w("|---|---:|---:|---:|")
        w(f"| all evidence codes | {len(allg):,} | **{len(hit)}** | {exp:.1f} |")
        w(f"| experimental evidence only | {len(expg):,} | **{len(hit_e)}** | "
          f"{(act_rate if direction is Direction.ACTIVATE else inh_rate) * len(expg):.1f} |")
        w("")
        w(f"Genes in this axis with a drug in the required direction: "
          + (", ".join(f"`{g}`" for g in hit[:30]) + (" ..." if len(hit) > 30 else "")
             if hit else "**none**") + "\n")
        w(f"Genes in this axis with a drug in the **opposite** direction: "
          f"{len(wrong)}. A repurposing proposal here has to avoid reaching for "
          f"those by convenience.\n")
        if hit:
            ratio = len(hit) / exp if exp else float("inf")
            w(f"That is **{ratio:.1f} times** the base-rate expectation for a "
              f"gene set of this size.")
            if ratio >= 1.2:
                w(f"So this axis is better supplied with activating drugs than "
                  f"the genome average, and unlike the direct axis it has "
                  f"something to work with.\n")
            else:
                w(f"So this axis is **no better supplied than the genome "
                  f"average**, and on this measure it is not a promising place "
                  f"to look. It differs from the direct axis in being non-empty "
                  f"rather than in being enriched, and that distinction should "
                  f"not be blurred: {len(hit)} available targets out of "
                  f"{len(allg):,} is what you would get by picking genes at "
                  f"random.\n")
            w("Either way this is a statement about pharmacological "
              "availability and not about whether modulating any of these genes "
              "would help this child, which nothing here addresses.\n")

    w("## 4. What this does not say\n")
    w("A gene appearing above means ChEMBL records a drug that acts on it in "
      "the required direction. It does not mean that drug is safe in a child, "
      "that it reaches the relevant tissue, that the GO annotation reflects the "
      "biology that matters here, or that modulating the gene would change "
      "anything about mosaic variegated aneuploidy. Every candidate that leaves "
      "this analysis still has to pass the safety screen in "
      "`src/mva/track2/safety.py`, and passing that makes it a research "
      "hypothesis and nothing more.\n")
    w("GO annotation sets are also not therapeutic targets. They are broad, they "
      "overlap, and membership is a claim about a process rather than about a "
      "point of intervention in it.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nWritten to {OUT}")


if __name__ == "__main__":
    main()
