#!/usr/bin/env python3
"""Is a structural stability calculation on p.Asn1002Lys possible at all?

Why ask before doing
--------------------
Plan section 7.5 permits structural work on one condition: that Track 1 yields a
specific missense in a protein with an **experimental** structure, and then only
as mechanistic illustration. This proband's second allele is p.Asn1002Lys, which
meets the first half. The report currently calls the variant hypomorphic on an
argument from viability rather than a measurement, and that is the weakest
load-bearing inference in either track, so substantiating it would be worth real
effort.

The condition to check first is not whether a structure exists but whether it
has **resolved coordinates at residue 1002**. A structure whose construct
declares the full protein tells you nothing if the density stops short, and a
stability calculation run on a residue that was never observed produces a number
that looks like evidence and is not. That is the anti-pattern CLAUDE.md warns
about, reached by accident rather than by choice.

Writes results/summaries/track2_structural_feasibility.md.
"""
from __future__ import annotations

import json
import pathlib
import urllib.request

UNIPROT = "O60566"          # BUB1B, BubR1
RESIDUE = 1002              # p.Asn1002Lys
PDBE = "https://www.ebi.ac.uk/pdbe/api"
OUT = pathlib.Path("results/summaries/track2_structural_feasibility.md")


def get(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": "mva-hackathon-2026"})
    try:
        with urllib.request.urlopen(req, timeout=60) as fh:
            return json.load(fh)
    except Exception:
        return {}


def main() -> None:
    entries = get(f"https://rest.uniprot.org/uniprotkb/{UNIPROT}.json"
                  f"?fields=xref_pdb,sequence")
    pdbs = [x["id"] for x in entries.get("uniProtKBCrossReferences", [])
            if x["database"] == "PDB"]
    seq = entries.get("sequence", {}).get("value", "")

    L: list[str] = []
    w = L.append
    w("# Track 2: is a structural calculation on p.Asn1002Lys feasible?\n")
    w("Generated by `scripts/32_structural_feasibility.py`. Sources: UniProt, "
      "PDBe.\n")
    w(f"UniProt {UNIPROT} (BubR1) is {len(seq)} residues and carries "
      f"**{len(pdbs)}** PDB entries: {', '.join(sorted(pdbs))}.\n")
    if len(seq) >= RESIDUE:
        w(f"Residue {RESIDUE} in the canonical sequence is **{seq[RESIDUE - 1]}**, "
          f"which independently confirms the p.Asn{RESIDUE}Lys annotation.\n")

    w("## Which entries map to residue 1002, and do they resolve it?\n")
    w("| PDB | Method | Resolution | UniProt range declared | Residue 1002 "
      "resolved? |")
    w("|---|---|---|---|---|")

    feasible = []
    stops: list[tuple[str, int]] = []
    for pdb in sorted(p.lower() for p in pdbs):
        maps = get(f"{PDBE}/mappings/uniprot/{pdb}")
        mappings = [m for acc, v in maps.get(pdb, {}).get("UniProt", {}).items()
                    if acc == UNIPROT for m in v.get("mappings", [])]
        covers = [m for m in mappings
                  if m["unp_start"] <= RESIDUE <= m["unp_end"]]
        if not covers:
            continue

        summ = get(f"{PDBE}/pdb/entry/summary/{pdb}").get(pdb, [{}])[0]
        expt = get(f"{PDBE}/pdb/entry/experiment/{pdb}").get(pdb, [{}])[0]
        method = ", ".join(summ.get("experimental_method") or ["unknown"])
        res = expt.get("resolution")

        # Declared coverage is not observed density, and the observed density of
        # some *other* protein in the same complex says nothing about this one.
        # An earlier version of this script took the maximum observed residue
        # across every chain in the entry and reported both APC/C structures as
        # feasible, because APC1 is numbered past 1002. Only the chains that map
        # to THIS UniProt accession count, and only in their own numbering.
        cov = get(f"{PDBE}/pdb/entry/polymer_coverage/{pdb}").get(pdb, {})
        our_chains = {m["chain_id"] for m in covers}
        observed_max = 0
        for mol in cov.get("molecules", []):
            for ch in mol.get("chains", []):
                if ch.get("chain_id") not in our_chains:
                    continue
                for o in ch.get("observed", []):
                    end = (o.get("end") or {}).get("residue_number")
                    if end:
                        observed_max = max(observed_max, end)

        # Author numbering can be offset from UniProt numbering; translate.
        # In these entries BubR1 is one chain of a large complex (chain Q in
        # 5KHU, chain S in 6TLJ) and is not the chain with the highest residue
        # numbers, which is why the chain restriction above is load-bearing.
        m0 = covers[0]
        offset = m0.get("start", {}).get("residue_number", m0["unp_start"]) - m0["unp_start"]
        target_author = RESIDUE + offset
        resolved = observed_max >= target_author
        if resolved:
            feasible.append(pdb.upper())
        else:
            stops.append((pdb.upper(), observed_max))
        w(f"| {pdb.upper()} | {method} | {res if res else 'n/a'} A | "
          f"{m0['unp_start']}-{m0['unp_end']} | "
          f"{'**yes**' if resolved else f'no, BubR1 density stops at residue {observed_max}'} |")

    w("")
    w("## Verdict\n")
    if feasible:
        w(f"**Feasible.** {', '.join(feasible)} resolve residue {RESIDUE}. Plan "
          f"section 7.5 applies and a stability calculation may proceed, with "
          f"its accuracy stated honestly and presented as mechanistic "
          f"illustration rather than as a variant-effect score.\n")
    else:
        w("**Not feasible, and not for want of a licence or a tool.**\n")
        detail = "; ".join(f"{k} stops at residue {v}" for k, v in stops)
        w(f"Every PDB entry that maps to residue {RESIDUE} does so by declaring "
          f"the full-length construct, and in none of them does the BubR1 "
          f"density reach it: {detail}. The kinase domain, residues 766 to 1050 "
          f"and the half of the protein this variant sits in, is unresolved in "
          f"both. Both are cryo-EM reconstructions of the anaphase-promoting "
          f"complex, in which BubR1 is a partly ordered component, at "
          f"resolutions where side-chain placement would not be determinable "
          f"even where density exists.\n")
        w("**So plan section 7.5's precondition is not met.** It permits "
          "structural work only for a missense in a protein with an experimental "
          "structure, and what exists here is an experimental structure of a "
          "different part of the protein.\n")
        w("**What we are declining to do instead, and why.** A predicted model "
          "would cover residue 1002, and running a stability calculation on it "
          "would produce a number. That number would be a statement about the "
          "prediction rather than about the protein, and presenting it as "
          "evidence for hypomorphism is precisely the anti-pattern recorded in "
          "`CLAUDE.md`: structure prediction standing in for a variant-effect "
          "measurement. The gap is worth more than a number that fills it "
          "without supporting it.\n")
        w("**Consequence for the report.** The claim that the second allele is "
          "hypomorphic remains an inference from viability, and the reason it "
          "cannot currently be measured computationally is now recorded rather "
          "than left as an unexplained absence. The experiment that would settle "
          "it is a functional assay of p.Asn1002Lys: kinase activity, checkpoint "
          "competence, or protein stability in a cell line.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
