#!/usr/bin/env python3
"""Is there precedent for a BUB1B kinase-domain missense causing MVA1?

The claim this addresses
------------------------
The Track 1 report calls allele 2, p.Asn1002Lys, presumed hypomorphic, and
labels that an inference from viability: complete BubR1 nullity is not
compatible with life, so a living compound heterozygote carrying one clear null
must retain function from the other allele. That reasoning is sound and it is
thin, because it appeals to a general principle rather than to anything about
this variant or this position.

There is a better question available, and it is answerable: **has this allelic
architecture been documented before, and where in the protein?**

Source
------
UniProt's curated natural-variant annotations for O60566 (BubR1), which carry
the disease association, the dbSNP identifier and the primary citation for each.
Nothing here is recalled; the identifiers come from the API.

Writes results/summaries/kinase_domain_precedent.md.
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib
import urllib.request

UNIPROT = "O60566"
OUR_RESIDUE = 1002          # p.Asn1002Lys
OUT = pathlib.Path("results/summaries/kinase_domain_precedent.md")


def get(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": "mva-hackathon-2026"})
    with urllib.request.urlopen(req, timeout=60) as fh:
        return json.load(fh)


def pubmed(pmids: list[str]) -> dict[str, dict]:
    if not pmids:
        return {}
    ids = ",".join(sorted(set(pmids)))
    d = get("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
            f"?db=pubmed&id={ids}&retmode=json").get("result", {})
    return {u: d[u] for u in d.get("uids", [])}


def main() -> None:
    d = get(f"https://rest.uniprot.org/uniprotkb/{UNIPROT}.json")
    feats = d.get("features", [])

    kinase = next(((f["location"]["start"]["value"], f["location"]["end"]["value"])
                   for f in feats
                   if f["type"] == "Domain" and "kinase" in (f.get("description") or "").lower()),
                  None)
    variants, nearby_sites = [], []
    for f in feats:
        loc = f.get("location", {})
        a = (loc.get("start") or {}).get("value")
        b = (loc.get("end") or {}).get("value")
        if a is None:
            continue
        if f["type"] == "Natural variant" and kinase and kinase[0] <= a <= kinase[1]:
            alt = f.get("alternativeSequence") or {}
            variants.append({
                "pos": a,
                "orig": alt.get("originalSequence", ""),
                "alt": ",".join(alt.get("alternativeSequences") or []),
                "desc": f.get("description") or "",
                "dbsnp": next((x["id"] for x in (f.get("featureCrossReferences") or [])
                               if x.get("database") == "dbSNP"), None),
                "pmids": [e["id"] for e in (f.get("evidences") or [])
                          if e.get("source") == "PubMed"],
            })
        if f["type"] in {"Modified residue", "Binding site", "Active site"} \
                and b is not None and abs(a - OUR_RESIDUE) <= 25:
            nearby_sites.append((f["type"], a, f.get("description") or ""))

    variants.sort(key=lambda v: v["pos"])
    cites = pubmed([p for v in variants for p in v["pmids"]])

    L: list[str] = []
    w = L.append
    w("# Precedent for a BUB1B kinase-domain missense in MVA1\n")
    w(f"Generated by `scripts/37_kinase_domain_precedent.py` on "
      f"{dt.date.today().isoformat()}. Source: UniProt {UNIPROT}, with citations "
      f"resolved through PubMed.\n")
    if kinase:
        w(f"The protein kinase domain spans residues **{kinase[0]} to {kinase[1]}**. "
          f"Our allele 2, p.Asn{OUR_RESIDUE}Lys, lies inside it.\n")

    w("## Curated MVA1 variants in the kinase domain\n")
    if not variants:
        w("None annotated. The precedent argument is unavailable.\n")
    else:
        w("| Residue | Change | Distance from 1002 | dbSNP | Description |")
        w("|---|---|---:|---|---|")
        for v in variants:
            w(f"| {v['pos']} | {v['orig']}>{v['alt']} | {abs(v['pos'] - OUR_RESIDUE)} | "
              f"{v['dbsnp'] or 'n/a'} | {v['desc']} |")
        w("")
        comp = [v for v in variants if "compound with nonsense" in v["desc"].lower()]
        w(f"**{len(comp)} of {len(variants)} are annotated as compound "
          f"heterozygous with a nonsense mutation**, which is precisely the "
          f"architecture proposed for this proband: a kinase-domain missense in "
          f"trans with a premature stop.\n")
        nearest = min(variants, key=lambda v: abs(v["pos"] - OUR_RESIDUE))
        w(f"The nearest is residue **{nearest['pos']}**, "
          f"{abs(nearest['pos'] - OUR_RESIDUE)} residues from ours.\n")

    if cites:
        w("### Citations\n")
        for pmid, r in sorted(cites.items()):
            au = (r.get("authors") or [{}])[0].get("name", "")
            w(f"- PMID {pmid}: {r.get('title')} *{r.get('fulljournalname')}*, "
              f"{r.get('pubdate')}. {au} et al.")
        w("")

    if nearby_sites:
        w("## Annotated functional sites within 25 residues\n")
        w("| Type | Residue | Description |")
        w("|---|---:|---|")
        for t, a, desc in sorted(nearby_sites, key=lambda x: x[1]):
            w(f"| {t} | {a} | {desc} |")
        w("")

    w("## What this does and does not establish\n")
    w("**Establishes** that MVA1 is repeatedly caused by a missense variant in "
      "this domain carried in trans with a nonsense allele, and that curated "
      "examples exist within a few residues of ours. The architecture we propose "
      "is the documented architecture for this disease rather than a construction "
      "of ours.\n")
    w("**Does not establish** that p.Asn1002Lys is hypomorphic. Proximity to a "
      "pathogenic residue is not evidence about a different residue, and no "
      "functional assay of this variant exists. The hypomorph model remains an "
      "inference; what changes is that it is now an inference with precedent "
      "rather than an appeal to viability alone.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
