#!/usr/bin/env python3
"""Does chemoprevention evidence exist for this disease, or must it be transferred?

The claim this tests
--------------------
Track 2's chemoprevention axis rests on transferring evidence from other
hereditary cancer predisposition syndromes, and the report calls that the
weakest link and the assumption doing most of the work. That claim was made from
a trial-registry search. A registry records what is being tested prospectively;
it does not record what has been published, including in animal models, which is
where an early chemoprevention signal would appear first.

So the same question is put to the published literature. If a `Bub1b` model
chemoprevention study exists, the transfer assumption is weaker than we said and
the report should cite it. If it does not, the limitation is confirmed by search
rather than asserted.

Writes results/summaries/chemoprevention_literature.md.
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib
import time
import urllib.parse
import urllib.request

EUTILS = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
OUT = pathlib.Path("results/summaries/chemoprevention_literature.md")

#: Narrowest first. The first two are the ones that would overturn the claim.
QUERIES = [
    ("Chemoprevention in a BUB1B model, the direct question",
     "Bub1b AND chemoprevention"),
    ("Chemoprevention in mosaic variegated aneuploidy",
     "mosaic variegated aneuploidy AND (chemoprevention OR cancer prevention)"),
    ("Tumour prevention in a Bub1b hypomorphic mouse, the falsification experiment",
     "Bub1b AND hypomorph* AND (prevention OR chemoprevention)"),
    ("Any chemoprevention in an aneuploidy or CIN model",
     "(aneuploidy OR chromosomal instability) AND chemoprevention AND mouse"),
    ("Rhabdomyosarcoma chemoprevention",
     "rhabdomyosarcoma AND (chemoprevention OR cancer prevention)"),
]


def esearch(term: str) -> tuple[int, list[str]]:
    q = urllib.parse.urlencode({"db": "pubmed", "retmode": "json",
                                "retmax": 20, "term": term})
    req = urllib.request.Request(f"{EUTILS}/esearch.fcgi?{q}",
                                 headers={"User-Agent": "mva-hackathon-2026"})
    with urllib.request.urlopen(req, timeout=60) as fh:
        d = json.load(fh)["esearchresult"]
    time.sleep(0.4)
    return int(d.get("count", 0)), d.get("idlist", [])


def esummary(pmids: list[str]) -> list[dict]:
    if not pmids:
        return []
    q = urllib.parse.urlencode({"db": "pubmed", "retmode": "json",
                                "id": ",".join(pmids)})
    req = urllib.request.Request(f"{EUTILS}/esummary.fcgi?{q}",
                                 headers={"User-Agent": "mva-hackathon-2026"})
    with urllib.request.urlopen(req, timeout=60) as fh:
        d = json.load(fh)["result"]
    time.sleep(0.4)
    return [d[u] for u in d.get("uids", [])]


def main() -> None:
    L: list[str] = []
    w = L.append
    w("# Does chemoprevention evidence exist for this disease?\n")
    w(f"Generated by `scripts/38_chemoprevention_literature.py` on "
      f"{dt.date.today().isoformat()}. Source: PubMed via NCBI E-utilities.\n")
    w("Track 2 says its chemoprevention candidates are transferred from other "
      "syndromes and calls that the weakest link. That was established from a "
      "trial registry, which records prospective trials and not published "
      "work, including animal studies where an early signal would appear first. "
      "This asks the literature the same question.\n")

    w("## Searches\n")
    w("| Question | Query | Hits |")
    w("|---|---|---:|")
    results = []
    for label, term in QUERIES:
        try:
            n, ids = esearch(term)
        except Exception as exc:
            w(f"| {label} | `{term}` | lookup failed: {exc} |")
            continue
        results.append((label, term, n, ids))
        w(f"| {label} | `{term}` | **{n}** |")
    w("")

    direct = [r for r in results if r[2] == 0 and "Bub1b" in r[1]]
    w("## What the searches return\n")
    for label, term, n, ids in results:
        if n == 0:
            w(f"**{label}: nothing.** No indexed publication matches `{term}`.\n")
            continue
        recs = esummary(ids[:5])
        w(f"**{label}: {n} hits.** The first {len(recs)}, to show what they "
          f"actually are:\n")
        for r in recs:
            w(f"- PMID {r.get('uid')}: {r.get('title')} *"
              f"{r.get('fulljournalname')}*, {r.get('pubdate')}")
        w("")

    w("## Reading this\n")
    if direct:
        w("**The direct question returns nothing.** No published study tests a "
          "chemoprevention agent in a `Bub1b` model. The transfer assumption in "
          "the Track 2 report is therefore not a gap we failed to fill; it is "
          "the state of the field, and the report's description of it as the "
          "weakest link stands, now confirmed by search rather than asserted.\n")
    w("Where a query does return hits, they are listed above so a reader can see "
      "that they are reviews, case reports and risk studies rather than "
      "prevention trials. A hit count alone would have been misleading, which is "
      "why the titles are printed rather than summarised.\n")
    w("## One hit is worth more than its count\n")
    w("PMID 24516128 (Lissa et al., *PNAS* 2014) reports that resveratrol and "
      "salicylate selectively reduce the fitness of **tetraploid** cells, acting "
      "through AMP-activated protein kinase, in cell lines and primary mouse "
      "epithelial cells in an `APC`-inactivation context.\n")
    w("Two things make it worth naming. **Aspirin reached our candidate table "
      "independently**, through a registry query that knew nothing about this "
      "paper, so the agent has a mechanistic rationale and not only a trial "
      "record. And **AMPK subunits reached our activatable list independently**, "
      "through the directional availability analysis: `PRKAA1`, `PRKAA2`, "
      "`PRKAG1`, `PRKAG2` and `PRKAG3` all carry an activating drug in ChEMBL. "
      "Two lines of evidence built for different purposes converge on the same "
      "target.\n")
    w("**It is not evidence for this disease, and the difference is the whole "
      "point.** Tetraploidy arising from cytokinesis failure is not "
      "whole-chromosome aneuploidy arising from a weakened spindle assembly "
      "checkpoint. The paper's context is `APC`-driven intestinal neoplasia, not "
      "`BUB1B`. It suggests a mechanistic route worth testing in the right model "
      "and it does not shorten the distance to this patient.\n")
    w("**The falsification experiment named in the Track 2 report remains "
      "unperformed**: a tumour-incidence study in a `Bub1b` hypomorphic mouse "
      "comparing a chemoprevention agent against control. Nothing found here "
      "substitutes for it.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
