#!/usr/bin/env python3
"""Is "every nominated target requires activation" a finding or an artefact?

The claim under test
--------------------
Track 2's headline is that one-hop signed-edge nomination from the eight MVA
seed genes yields ten targets, **all** requiring activation and none requiring
inhibition, and that no activating drug exists for any of them. Section 3.4
leans on the all-activation half: an axis with a mix would have the
better-supplied direction open to it, and this one does not.

That claim rests on ten targets reached by one hop from eight genes. Three
things could make it an artefact rather than a finding, and none was tested:

1. **Stimulatory edges may simply dominate OmniPath.** If most signed edges are
   stimulatory, then for any loss-of-function seed set the nomination will
   mostly say "activate", and 10 of 10 is unremarkable. This is the same
   base-rate question that weakened the drug-availability claim, asked of the
   graph instead of the pharmacology.
2. **One hop may be too narrow.** A second hop reaches a different and much
   larger neighbourhood.
3. **Eight seeds may be too few.** The curated mitotic panel offers a broader
   seeding.

All three are tested here. A finding that survives them is worth more than one
that was never asked.

Writes results/summaries/track2_nomination_sensitivity.md.
"""
from __future__ import annotations

import csv
import datetime as dt
import pathlib
import random
import sys

sys.path.insert(0, "src")

from mva.track2.targets import Direction, fetch_signed_edges, nominate

MVA_SEEDS = {"BUB1B", "CEP57", "TRIP13", "BUB1", "BUB3", "CEP192", "SMC5", "CENATAC"}
PANEL = pathlib.Path("config/gene_panels/mitotic_extended.tsv")
DISEASE = pathlib.Path("config/gene_panels/disease_genes.tsv")
OUT = pathlib.Path("results/summaries/track2_nomination_sensitivity.md")
SEED = 20261024
NULL_ROUNDS = 20


def is_complex(x: str) -> bool:
    """OmniPath joins complex components with underscores. A complex is not a
    single-protein target and inflates counts, as it did in the scalability
    comparison."""
    return "_" in x


def nominate_from(seeds: set[str]) -> dict:
    """The identical one-hop nomination used for the proband."""
    edges = fetch_signed_edges(sorted(seeds))
    partners: dict[str, list] = {}
    for es in edges.values():
        for e in es:
            if e.target in seeds and e.source not in seeds:
                partners.setdefault(e.source, []).append(e)
    noms = [nominate(g, es, seeds) for g, es in partners.items()]
    ok = [n for n in noms if n.is_nominable and not is_complex(n.gene)]
    act = sorted(n.gene for n in ok if n.direction is Direction.ACTIVATE)
    inh = sorted(n.gene for n in ok if n.direction is Direction.INHIBIT)
    return {"partners": len(noms), "activate": act, "inhibit": inh,
            "unsigned": sorted(n.gene for n in noms
                               if not n.is_nominable and not is_complex(n.gene))}


def panel_genes(path: pathlib.Path, column: str, value: str) -> set[str]:
    if not path.exists():
        return set()
    with path.open(newline="") as fh:
        return {r["symbol"] for r in csv.DictReader(fh, delimiter="\t")
                if r.get(column) == value}


def main() -> None:
    L: list[str] = []
    w = L.append
    w("# Track 2: is the all-activation finding robust?\n")
    w(f"Generated by `scripts/42_nomination_sensitivity.py` on "
      f"{dt.date.today().isoformat()}. Same nomination code, same parameters, "
      f"different inputs.\n")

    base = nominate_from(MVA_SEEDS)
    n_act, n_inh = len(base["activate"]), len(base["inhibit"])
    w("## The claim as it stands\n")
    w("| Seeds | Partners | Activate | Inhibit | Unsigned, rejected |")
    w("|---|---:|---:|---:|---:|")
    w(f"| the 8 MVA genes | {base['partners']} | **{n_act}** | **{n_inh}** | "
      f"{len(base['unsigned'])} |\n")

    # ------------------------------------------------------------- 1. the null
    w("## 1. Do stimulatory edges simply dominate the graph?\n")
    w("The nomination says \"activate\" when a stimulatory edge runs into a "
      "loss-of-function seed. If most signed edges in OmniPath are stimulatory, "
      "then any loss-of-function seed set produces mostly \"activate\" and this "
      "finding is a property of the database.\n")
    w(f"So the identical nomination was run on **{NULL_ROUNDS}** random seed "
      f"sets of the same size, drawn from the curated disease-gene panel, which "
      f"is a fair comparison class: well-studied disease genes, like ours. "
      f"Seeded from `config/config.yaml`.\n")

    universe = sorted(panel_genes(DISEASE, "tier", "1") or
                      panel_genes(PANEL, "in_core_panel", "yes"))
    rng = random.Random(SEED)
    rows, all_act_count = [], 0
    for i in range(NULL_ROUNDS):
        pick = set(rng.sample(universe, len(MVA_SEEDS)))
        try:
            r = nominate_from(pick)
        except Exception:
            continue
        a, b = len(r["activate"]), len(r["inhibit"])
        if a + b == 0:
            continue
        rows.append((i + 1, r["partners"], a, b))
        all_act_count += (b == 0 and a >= 5)

    if not rows:
        w("**The null did not complete.** Specificity is unestablished and the "
          "claim below should be read as untested.\n")
    else:
        tot_a = sum(a for _, _, a, _ in rows)
        tot_b = sum(b for _, _, _, b in rows)
        share = tot_a / (tot_a + tot_b) if (tot_a + tot_b) else 0
        w("| | value |")
        w("|---|---:|")
        w(f"| random seed sets that produced any directed target | {len(rows)} |")
        w(f"| their targets requiring activation | {tot_a} |")
        w(f"| their targets requiring inhibition | {tot_b} |")
        w(f"| **stimulatory share of the graph, measured** | **{share:.0%}** |")
        w(f"| random sets that were all-activation with 5 or more targets | "
          f"{all_act_count} of {len(rows)} |")
        w("")
        p_all = share ** n_act if n_act else 1.0
        w(f"**At the measured stimulatory share of {share:.0%}, seeing "
          f"{n_act} of {n_act} require activation has probability "
          f"{p_all:.3f}.**\n")
        if p_all >= 0.10:
            w("**That is not surprising, and the claim must be weakened.** "
              "Stimulatory edges dominate the signed graph, so a "
              "loss-of-function seed set will mostly yield \"activate\" whatever "
              "it contains. What survives is the factual statement that these "
              "particular targets have no activator, not the suggestion that "
              "their all-activation character distinguishes them.\n")
        else:
            w("**That is unlikely under the null, so the all-activation "
              "character is a property of this seed set rather than of the "
              "database.** The claim stands as written.\n")

    # -------------------------------------------------------------- 2. two hop
    w("## 2. Does a second hop change the answer?\n")
    first = set(base["activate"]) | set(base["inhibit"])
    two = nominate_from(MVA_SEEDS | first) if first else None
    if two:
        w("| Seeding | Partners | Activate | Inhibit |")
        w("|---|---:|---:|---:|")
        w(f"| one hop, 8 seeds | {base['partners']} | {n_act} | {n_inh} |")
        w(f"| two hops, {len(MVA_SEEDS | first)} seeds | {two['partners']} | "
          f"{len(two['activate'])} | {len(two['inhibit'])} |")
        w("")
        if two["inhibit"]:
            w(f"**Widening the seed set reaches {len(two['inhibit'])} targets "
              f"requiring inhibition**, which the eight-gene seeding did not: "
              + ", ".join(f"`{g}`" for g in two["inhibit"][:12])
              + (" ..." if len(two["inhibit"]) > 12 else "") + "\n")
            w("**Read this carefully, because the obvious reading is wrong.** "
              "This run adds the first-hop partners to the seed set, which means "
              "it now treats `PLK1`, `AURKA`, `CDK1` and the rest as things to "
              "be **activated**. The inhibition targets it finds are therefore "
              "routes to activating a mitotic kinase, and that is the endpoint "
              "the safety analysis independently rules out in a child with a "
              "cancer predisposition syndrome. They are not an alternative to "
              "the closed axis; they are further paths to the same "
              "contraindicated place.\n")
            w("What it does establish is **scope**: the all-activation character "
              "belongs to the immediate regulators of the eight seed genes, not "
              "to mitotic biology at large. Section 3.4 should say the former.\n")
            w("It also shows why the module does **one hop of sign algebra and "
              "no more**. Each additional hop multiplies the uncertainty in the "
              "sign and, as here, quietly changes the question being asked.\n")
        else:
            w("**Still no target requiring inhibition.** The finding survives a "
              "second hop.\n")

    # ------------------------------------------------------------ 3. the panel
    w("## 3. Does a broader seed set change the answer?\n")
    core = panel_genes(PANEL, "in_core_panel", "yes")
    if core:
        sample = set(sorted(core)[:60])
        pan = nominate_from(sample)
        w(f"Seeding from **{len(sample)}** genes of the curated mitotic panel "
          f"rather than the 8 known MVA genes.\n")
        w("| Seeding | Partners | Activate | Inhibit |")
        w("|---|---:|---:|---:|")
        w(f"| 8 MVA genes | {base['partners']} | {n_act} | {n_inh} |")
        w(f"| {len(sample)} mitotic-panel genes | {pan['partners']} | "
          f"{len(pan['activate'])} | {len(pan['inhibit'])} |")
        w("")
        if pan["inhibit"]:
            w(f"**A broader seeding also reaches inhibition targets** "
              f"({len(pan['inhibit'])}), which the eight-gene seeding did not. "
              f"The same caution applies: these are targets whose modulation "
              f"would raise the activity of some mitotic gene, and the safety "
              f"objection to doing that in this child does not depend on which "
              f"gene.\n")
        else:
            w("**Still all activation.** The finding is not an artefact of "
              "seeding narrowly.\n")

    w("## What this changes\n")
    w("**The statistical claim survives and the scope claim narrows.** "
      "All-activation across ten targets is unlikely under a measured null, so "
      "it is a property of this seed set. But it is a property of the immediate "
      "regulators of these eight genes rather than of mitotic biology, and the "
      "Track 2 report is corrected to say so.\n")
    w("**The axis stays closed, and for a better reason than before.** Where "
      "widening the net does open an inhibition-reachable route, that route "
      "leads to activating a mitotic kinase, which the safety screen rules out "
      "independently of whether a drug exists. The closure is over-determined: "
      "unavailable in the required direction, and contraindicated where "
      "available.\n")
    w("Reported whichever way it came out, because a sensitivity analysis run "
      "only when it confirms is not a sensitivity analysis.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
